sokol_app.h win32: implements optional per monitor DPI awareness
floooh/sokol pull request #610
Opened 2022-01-13 13:55 UTC by tjachmann

For win32 adds per monitor DPI arewareness, so the window's DPI gets updated when it is moved to a monitor with a different DPI. 
 - Reverts to system DPI, if an older windows then Windows 10 Creators Update is used
 - Although I think this behaviour should be the default, I made it optional for now.  See flag in backend-specific options in app_desc

2022-01-13 16:28 UTC, floooh requested changes

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +    bool win32_default_size;            // if true, set the output console codepage to UTF-8
Please fix the comment.

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
please remove whitespace

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
please remove 1 line of whitespace

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +                }
I think it would be better to wrap this code into a small helper function _sapp_win32_dpi_changed().

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
Whitespace :)

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +    DECLARE_HANDLE(DPI_AWARENESS_CONTEXT_T);
Should this be moved up into:

https://github.com/floooh/sokol/blob/b2f60754841c0bbfad47da86974e43e494f11bef/sokol_app.h#L2114-L2127

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
whitespace :)

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
whitespace :)

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
whitespace :)

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
whitespace

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
whitespace

2022-01-13 16:28 UTC, floooh commented on sokol_app.h
> +
whitespace

2022-01-13 16:30 UTC, floooh commented
Looks good!

Sorry about all the "remove whitespace" requests.

The new ```win32_default_size``` config setting is unrelated to the DPI changes though right?

2022-01-15 11:53 UTC, floooh commented
...I've been sleeping over the default window size thing, and I think it's better to turn this into a cross-platform-thing by simply providing zero-initialized width and height  in sapp_desc. I'll check if the other desktop platforms also provide some sort of default-window-size feature (on web and mobile, the size is ignored anyway).

You don't need to change the PR for this, I'll take care of that during merging.

I'll first take care of https://github.com/floooh/sokol/pull/611 and then start integrating your PR (with the default-size changes).

2022-01-16 13:18 UTC, floooh commented
Looks like you are compiling as C++? There's a ```nullptr``` in the call to SetWindowPos ;)

I'll clean up that stuff in a merge branch, I'll probably also move the LoadLibrary() and GetProcAddress() call out of the dpi-changed code path into the initialization code.

Also I didn't notice the -4 constant at first here:

```
fn_setprocessdpiawarenesscontext((DPI_AWARENESS_CONTEXT_T)-4)
```

Is there a human readable name for that constant?

2022-01-16 13:37 UTC, floooh commented
Ok, a question:

The per-monitor DPI code-path is currently enabled with ```sapp_desc.win32_per_monitor_dpi_v2```. Is there a situation where one wouldn't want to set this to true? If not I would remove this config setting.

2022-01-16 14:29 UTC, floooh commented
Here's my attempt to somewhat simplify the DPI setup code in _sapp_win32_dpi_init(), does that look alright to you?

```c
    /*
        NOTE on SetProcessDpiAware() vs SetProcessDpiAwareness() vs SetProcessDpiAwarenessContext():

        These are different attempts to get DPI handling on Windows right, from oldest
        to newest. SetProcessDpiAwarenessContext() is required for the new
        DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 method.
    */
    if (fn_setprocessdpiawareness) {
        if (_sapp.desc.high_dpi) {
            /* app requests HighDPI rendering, first try the Win10 Creator Update per-monitor-dpi awareness,
               if that fails, fall back to system-dpi-awareness
            */
            _sapp.win32.dpi.aware = true;
            DPI_AWARENESS_CONTEXT_T per_monitor_aware_v2 = (DPI_AWARENESS_CONTEXT_T)-4;
            if (!(fn_setprocessdpiawarenesscontext && fn_setprocessdpiawarenesscontext(per_monitor_aware_v2))) {
                // fallback to system-dpi-aware
                fn_setprocessdpiawareness(PROCESS_SYSTEM_DPI_AWARE);
            }
        }
        else {
            /* if the app didn't request HighDPI rendering, let Windows do the upscaling */
            _sapp.win32.dpi.aware = false;
            fn_setprocessdpiawareness(PROCESS_DPI_UNAWARE);
        }
    }
    else if (fn_setprocessdpiaware) {
        // fallback for Windows 7
        _sapp.win32.dpi.aware = true;
        fn_setprocessdpiaware();
    }
```

2022-01-16 14:55 UTC, floooh commented
FYI: this is the temporary merge branch I'm currently working on:

https://github.com/floooh/sokol/compare/tjachmann-master

2022-01-16 15:15 UTC, tjachmann commented
> Looks like you are compiling as C++? There's a `nullptr` in the call to SetWindowPos ;)

 Yep and ops :) 

> fn_setprocessdpiawarenesscontext((DPI_AWARENESS_CONTEXT_T)-4)

You could alternativly replace the beginning of the _sapp_win32_init_dpi like this

#ifndef _DPI_AWARENESS_CONTEXTS_
    DECLARE_HANDLE(DPI_AWARENESS_CONTEXT);
#endif

#ifndef DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2
    #define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 (DPI_AWARENESS_CONTEXT)-4
#endif

typedef BOOL(WINAPI * SETPROCESSDPIAWARE_T)(void);
typedef bool (WINAPI * SETPROCESSDPIAWARENESSCONTEXT_T)(DPI_AWARENESS_CONTEXT); // since Windows 10, version 1703`


And then use the DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 instead of -4. A bit longer, but somehow cleaner.

2022-01-16 15:20 UTC, tjachmann commented
> Ok, a question:
> 
> The per-monitor DPI code-path is currently enabled with `sapp_desc.win32_per_monitor_dpi_v2`. Is there a situation where one wouldn't want to set this to true? If not I would remove this config setting.

I also think it should become the default. The only issue I could currently imagine is that when you pass in an concrete window size on creation, then the initial window creating does not respect per-monitor DPI.  More exactly if windows decides to create the window on another monitor the where you query the DPI.

2022-01-16 15:20 UTC, floooh commented
I just did this, I think that's alright. It's just the -4 without context as function arg I had a problem with.

```c
DPI_AWARENESS_CONTEXT_T per_monitor_aware_v2 = (DPI_AWARENESS_CONTEXT_T)-4;
```

2022-01-16 15:23 UTC, floooh commented
> More exactly if windows decides to create the window on another monitor the where you query the DPI.

Yep, but that's not supported currently anyway, and for this the code which initially queries the DPI would need to be changed anyway. I just removed that config item in the merge branch and I think it's working ok. So far I have only tested on a single-monitor setup by changing the DPI in the system settings, but next I'll check on my HighDPI laptop with a 1080p monitor attached...

2022-01-16 15:25 UTC, tjachmann commented
> Here's my attempt to somewhat simplify the DPI setup code in _sapp_win32_dpi_init(), does that look alright to you?
> 
> ```c
>     /*
>         NOTE on SetProcessDpiAware() vs SetProcessDpiAwareness() vs SetProcessDpiAwarenessContext():
> 
>         These are different attempts to get DPI handling on Windows right, from oldest
>         to newest. SetProcessDpiAwarenessContext() is required for the new
>         DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 method.
>     */
>     if (fn_setprocessdpiawareness) {
>         if (_sapp.desc.high_dpi) {
>             /* app requests HighDPI rendering, first try the Win10 Creator Update per-monitor-dpi awareness,
>                if that fails, fall back to system-dpi-awareness
>             */
>             _sapp.win32.dpi.aware = true;
>             DPI_AWARENESS_CONTEXT_T per_monitor_aware_v2 = (DPI_AWARENESS_CONTEXT_T)-4;
>             if (!(fn_setprocessdpiawarenesscontext && fn_setprocessdpiawarenesscontext(per_monitor_aware_v2))) {
>                 // fallback to system-dpi-aware
>                 fn_setprocessdpiawareness(PROCESS_SYSTEM_DPI_AWARE);
>             }
>         }
>         else {
>             /* if the app didn't request HighDPI rendering, let Windows do the upscaling */
>             _sapp.win32.dpi.aware = false;
>             fn_setprocessdpiawareness(PROCESS_DPI_UNAWARE);
>         }
>     }
>     else if (fn_setprocessdpiaware) {
>         // fallback for Windows 7
>         _sapp.win32.dpi.aware = true;
>         fn_setprocessdpiaware();
>     }
> ```

Looks good

2022-01-16 16:24 UTC, floooh commented
Hmm, I need to fix sokol_imgui.h somehow, the scaling is now too big when moving from a HighDPI to a LowDPI monitor. I guess there are some places where the DPI scale factor isn't expected to change.

Interestingly, with the old SetProcessDPIAwareness() it worked as expected. I'll continue working on this stuff for the next few days I think.

![Uploading Untitled.png…]()

2022-01-16 16:29 UTC, floooh commented
...looks like image upload is currently borked... I can't even fix the previous comment hmm...

2022-01-17 16:29 UTC, floooh commented
...while at it I also implemented per-monitor DPI for macOS (together with a generally more robust dpi_scale handling code).

Also reminder to self: check if on Windows an SAPP_EVENTTYPE_RESIZED is issued when the DPI changes (it should, as a "delayed side effect" of the SetWindowPos() call.

2022-01-18 15:35 UTC, tjachmann commented
Ah to compile with legacy SDKs (WINVER < 0x0601), need to check if the DPI message is defined...

#ifndef WM_DPICHANGED
    #define WM_DPICHANGED                   0x02E0
#endif

2022-01-18 17:24 UTC, floooh commented
> Ah to compile with legacy SDKs (WINVER < 0x0601), need to check if the DPI message is defined...

Good point, I'll add that. The merge will most likely happen tomorrow btw. Got a bit tangled up with fixing the new timing code when moving the window between displays with a different refresh rate.

2022-01-19 12:06 UTC, merged

2022-01-19 12:07 UTC, floooh commented
Ok merged. Changelog entry (18-Jan-2022): https://github.com/floooh/sokol/blob/master/CHANGELOG.md

2022-01-19 13:20 UTC, floooh commented
PS: as I mentioned above, I haven't included the default-size handling in this PR. I will come up with a different solution (after looking into the sokol_audio.h sample format problem).

2022-01-28 15:34 UTC, floooh commented
@tjachmann FYI, the default-window-size changes are now implemented (see: https://github.com/floooh/sokol/pull/623)